// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Load struct {
	ID            string           `json:"id"`
	Material      string           `json:"material"`
	AverageWeight int32            `json:"averageWeight"`
	Unit          string           `json:"unit"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	Operator      string           `json:"operator"`
	Shift         string           `json:"shift"`
}
