CREATE TABLE IF NOT EXISTS load_record (
    id VARCHAR(36) NOT NULL,
    material VARCHAR(100) NOT NULL,
    average_weight INT NOT NULL,
    unit VARCHAR(5) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    operator VARCHAR(255) NOT NULL,
    shift VARCHAR(5) NOT NULL,
    PRIMARY KEY (id),
    INDEX (id)
);
