CREATE TABLE IF NOT EXISTS loads (
    id VARCHAR(26) PRIMARY KEY,
    material VARCHAR(100) NOT NULL,
    average_weight INTEGER NOT NULL,
    unit VARCHAR(5) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    timezone VARCHAR(50) DEFAULT 'UTC',
    operator VARCHAR(255) NOT NULL,
    shift VARCHAR(5) NOT NULL
);
