CREATE TABLE IF NOT EXISTS load_record (
    id INT AUTO_INCREMENT PRIMARY KEY,
    material VARCHAR(255) NOT NULL,
    average_weight INT NOT NULL,
    unit VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    operator VARCHAR(100) NOT NULL,
    shift VARCHAR(50) NOT NULL
);
